import { circlePackingMarkup } from "./circle-packing.js";
import { penroseMarkup } from "./penrose-rhombs.js";
import { regularTilingMarkup } from "./regular-tilings.js";
import { starCrossSvg } from "./star-cross.js";
import { translatedBoundaryMarkup } from "./translated-boundary.js";

export const goldenRatio = () => (1 + Math.sqrt(5)) / 2;
export const regularInteriorAngle = (sides) => 180 * (sides - 2) / sides;
export const vertexCount = (sides) => 360 / regularInteriorAngle(sides);
export const hexPackingFraction = () => Math.PI / (2 * Math.sqrt(3));

const tetrominoes = [[0,0,1,0,2,0,3,0],[0,0,1,0,0,1,1,1],[0,0,1,0,2,0,1,1],[0,0,0,1,1,1,2,1],[2,0,0,1,1,1,2,1],[1,0,2,0,0,1,1,1],[0,0,1,0,1,1,2,1]];

function tetrominoMarkup() {
  return tetrominoes.map((shape, index) =>
    `<g transform="translate(${34 + index * 86} ${120 + (index % 2) * 82})">${Array.from({ length: 4 }, (_, cell) =>
      `<rect class="${index % 2 ? "tile-accent" : "tile-cool"}" x="${shape[cell * 2] * 22}" y="${shape[cell * 2 + 1] * 22}" width="21" height="21"></rect>`
    ).join("")}</g>`
  ).join("");
}

const visualLabels = {
  "regular-plane-tilings": "Exact edge-to-edge regular tiling",
  "hexagonal-circle-packing": "Exact equal-circle triangular-lattice packing",
  "penrose-rhombs": "Valid finite Penrose rhomb patch generated by pentagrid projection",
  "escher-plane-division": "Exact translated-boundary tiling",
  "tetris-tetrominoes": "Exact enumeration of the seven one-sided tetrominoes"
};

export function tessellationSvg(topicId, state = { sides: 3, deformation: 12 }) {
  let body;
  if (topicId === "regular-plane-tilings") body = regularTilingMarkup(state.sides);
  else if (topicId === "hexagonal-circle-packing") body = circlePackingMarkup();
  else if (topicId === "kashan-star-cross") return starCrossSvg(state.mode || "pattern");
  else if (topicId === "penrose-rhombs") body = penroseMarkup();
  else if (topicId === "tetris-tetrominoes") body = tetrominoMarkup();
  else body = translatedBoundaryMarkup(state.deformation);
  const label = visualLabels[topicId] || "Analytical geometry reconstruction";
  return `<svg viewBox="0 0 640 340" role="img" aria-label="${label}"><g>${body}</g></svg>`;
}

export function tetrominoCellCounts() {
  return tetrominoes.map((shape) => shape.length / 2);
}
