/*
 * Gridline service worker (SPEC.md C5; ARCHITECTURE.md §5.8; D-070, D-073).
 *
 * Hand-written on purpose (D-033): offline honesty must be provable from a
 * static list, which a caching strategy cannot give. No Workbox, no
 * dependency.
 *
 *  1. One list per surface. tools/inject-sw-manifest.mjs writes BUILD below:
 *     `shell`, `shared`, `course` and `companion`, each entry `{ path,
 *     sha256 }`, path relative to this worker's scope. The page registers
 *     `./sw.js?surface=<sorted surfaces used in this browser>`, and install
 *     fetches only those surfaces (C5.6): the phone never downloads the
 *     desktop surface.
 *  2. Install is all or nothing (C5.4, G2R-39). Every listed file is fetched
 *     with `?v=<first 16 hex of manifestHash>`, so a stale CDN copy of an
 *     unhashed URL (index.html, the icons, the map crop) is not used, and its
 *     SHA-256 is compared with the list. One missing file or one wrong byte
 *     fails the install; the old version keeps serving.
 *  3. The cache name comes from the content: `mrt-precache-<16 hex>-<surfaces
 *     joined by +>` (SPEC-SCHEMAS.md §5.11). It changes exactly when a listed
 *     file or the surface set changes, so an install never writes into the
 *     cache the active worker serves.
 *  4. A new version waits until every Gridline tab is closed (E22). There is
 *     no page-started swap. Activate deletes only the other `mrt-` caches,
 *     because other pages on the origin keep their own (E28).
 *  5. Readiness is asked for, never volunteered: the page shows "Offline pack
 *     ready" only after MRT_QUERY_OFFLINE_READY answers ready for its surface.
 *  6. Nothing cross-origin is ever cached or answered (D-023): licence
 *     position and offline honesty both depend on it.
 */

'use strict'

/* __BUILD_ASSETS_START__ */
/* Generated by tools/inject-sw-manifest.mjs. Do not edit by hand. */
const BUILD = {
  "manifestHash": "0f41acefae425ed40300c3207ec4722ba75005be0292ed73e1f8a619aee24de9",
  "lists": {
    "shell": [
      {
        "path": "icons/icon-192.png",
        "sha256": "f7bf2aaafbba1ebe85937e38b8741b61e49e73660352be204d3aa2f452e29086"
      },
      {
        "path": "icons/icon-512.png",
        "sha256": "69d6e8771c73b16d383d3092106019dd66fdf26aac9f5f5412c13ab6c5cacb5c"
      },
      {
        "path": "icons/maskable-512.png",
        "sha256": "0b5c044a1283ee9f94cd0b0c02b211d199315eb1f2789a7ed271d56ed023bed6"
      },
      {
        "path": "index.html",
        "sha256": "fbf8e577c24a438390e257bad1f41ab8005b225de3473520ca7d8da51ac39db7"
      },
      {
        "path": "licences/ibm-plex-LICENSE.txt",
        "sha256": "37784b44044a4ffd9256702b7c0982c37e5c8887ba90c6dca0479aea93dc898d"
      },
      {
        "path": "licences/space-grotesk-OFL.txt",
        "sha256": "c6dec685825f73b18c20926fddc65e8315642e12986f15db0699170940a09efc"
      },
      {
        "path": "manifest.webmanifest",
        "sha256": "bf5e967812ebeaad95c3b3f611972b27f13e9db203d2dc3a4026dae0b98f56c7"
      }
    ],
    "shared": [
      {
        "path": "assets/companion-BGFUudra.js",
        "sha256": "16ec04fe999e5820244b9d8ef8231a62ae0571c462165b3598ed0631950b50a8"
      },
      {
        "path": "assets/companion-CETaDIzi.css",
        "sha256": "d236becaa33c56a439dcf88e3aec1d0baf516e3dfd12c15f6c565ad78c46e315"
      },
      {
        "path": "assets/ibm-plex-mono-400-DMJ8VG8y.woff2",
        "sha256": "08949f728dc52d528e69b1667d15c89a5686a4ee9a296ff90983985f99c380f7"
      },
      {
        "path": "assets/ibm-plex-mono-500-DSY6xOcd.woff2",
        "sha256": "01d285447409c8a588692162439a038b8cbd7871309ee20267b0d2d91c6e8e22"
      },
      {
        "path": "assets/ibm-plex-sans-400-CDDApCn2.woff2",
        "sha256": "3b646991d30055a93a4ecc499713d4347953a74a947ecab435ab72070cbdab0e"
      },
      {
        "path": "assets/ibm-plex-sans-500-6ng42L7E.woff2",
        "sha256": "0717336fb31fcdcde4b8deb3675bb4a0f7f6d484864afcd6751ac29975962203"
      },
      {
        "path": "assets/ibm-plex-sans-600-CuJfVYMP.woff2",
        "sha256": "8960851d691c054ed38e259bdcf1a6190d157b4203ed5bb32c632a863fb8ec2f"
      },
      {
        "path": "assets/index-DCp8joYQ.js",
        "sha256": "da700c64a665cb8a5b2fe91c055048670d4be3fcbbfbca4f6ac23cb377c9fa0c"
      },
      {
        "path": "assets/rolldown-runtime-BpQH8Ho1.js",
        "sha256": "f42a7e25f42fd00b0935f3a7b06f4429238b50b6798b53c273e30d7095f9e94e"
      },
      {
        "path": "assets/shared-CP1SpTuY.js",
        "sha256": "5ee694b9464bb17cd8c7bb63a0b365873ab6e9f70d6f330a92b3bb533a9e3acf"
      },
      {
        "path": "assets/shared-aFzNI-6S.css",
        "sha256": "8371b4513dc943bf0ae17ab9d6ceb439b8b4a0f410e9f921f9545cb3e6020548"
      },
      {
        "path": "assets/space-grotesk-500-lFbtlQH6.woff2",
        "sha256": "1b1a8131d9edf975d9decee81e2f2bf504812f7a4f498e5500f28a613e22e64c"
      },
      {
        "path": "assets/space-grotesk-600-DjKNqYRj.woff2",
        "sha256": "685bbbf69fa616df1ef81847c85fc76be097ddfb3468ff2257be54511ab3130f"
      }
    ],
    "course": [
      {
        "path": "assets/ReferenceSection-B_6nny9X.js",
        "sha256": "a5495850882209f355b2139838cea54352a38b906d9eef624512650d069d4a21"
      },
      {
        "path": "assets/ReferenceSection-DEK-iZmQ.css",
        "sha256": "e588094724a6022a3709a7949a4fb16362d9f974b2831fd5c0a024ff6a25feec"
      },
      {
        "path": "assets/Settings-BYmkW5oL.js",
        "sha256": "a0279911c9c34b614d573843d72583470348b2c167bf34a7956486ef1dbfed27"
      },
      {
        "path": "assets/course-arcade-3Gd3krhF.css",
        "sha256": "a4eae269c778b3379168c08164f39ffbb78fe15f455eeed64b201f8c816ba861"
      },
      {
        "path": "assets/course-arcade-BBjxaBlf.js",
        "sha256": "7a1c03926a0d5b5639da802b5c11bc753b8733fafc40b3ac92541496f0c96d76"
      },
      {
        "path": "assets/course-curriculum-CyIX7dQE.js",
        "sha256": "cc5249d5ec11af202c27805c79070593afef02f25141179385d4b0a51e29d87b"
      },
      {
        "path": "assets/course-curriculum-afMq3IXl.css",
        "sha256": "2530bc40ad53f8dbd40838ee3b859aba0da2a87c01d38de018582467f1b3c974"
      },
      {
        "path": "assets/course-lesson-map-distance-to-ground-distance-CXyhUSwj.js",
        "sha256": "e3e81421fd8bd75ce42f1919a59e0b2439a145f7e79748fa1e658a61f5dabfea"
      },
      {
        "path": "assets/course-lesson-six-figure-grid-references-kLRCUeIY.js",
        "sha256": "ba595db23ccea20aecb7e69d60e703cfc70505eb5934f9b5ea770318466243c9"
      },
      {
        "path": "assets/course-lessons-DVmnbsCT.css",
        "sha256": "d036c10747502770e49ba6642d01a93d7facb6033edca78031baf5fc588ef02a"
      },
      {
        "path": "assets/course-lessons-Dp6Cm7FM.js",
        "sha256": "96a28fedd3812304970e1914ac8851de4d54f942e26056d5bbe927820dc22a81"
      },
      {
        "path": "assets/course-progress-D5Vqewwq.js",
        "sha256": "a6b8fe3e99581b28fc7129d744b0aa6a3c0fbb0487831c8796241efad119c352"
      },
      {
        "path": "assets/course-templates-DkV5nL7C.js",
        "sha256": "f458cdb7246e518188d0eef5acbac69da17149e460a77134f57a6262f6c6f0ff"
      },
      {
        "path": "assets/scale-1-50000-Mz33qHc3.svg",
        "sha256": "41575516b233393fd525ffdb839d934d95fc36adbabe6165aaee90c9aa2055ca"
      },
      {
        "path": "assets/sheet-margin-KwCMArl3.svg",
        "sha256": "512fd2bf3119840b762e8cd3fe4acb0daa83bb2386ba7e407144c50b6df3ace8"
      },
      {
        "path": "assets/we-43mm-Bp-Murfi.svg",
        "sha256": "8fe4d47ddc03e0d6f34bc554f8333f4a93b3628ff001bac875be48a5d52b5bad"
      },
      {
        "path": "assets/we-984531-CGtalj4f.svg",
        "sha256": "ac89d3ca8176f74b3428cc9a9dfb65a9157be39a3ddbf79e5dce4fc9b8563834"
      },
      {
        "path": "licensed-maps/011e03_scale_distance_crop_v1.png",
        "sha256": "8a1ca00c4bbc95e204995c37cb598daabe1ae85b57be2dd9116153faef55a34d"
      }
    ],
    "companion": []
  }
}
/* __BUILD_ASSETS_END__ */

const KNOWN_SURFACES = ['companion', 'course']
const SCOPE = self.registration.scope

/** The surfaces this registration names, sorted; null when it names one we do not know (fail closed). */
function registeredSurfaces() {
  const raw = new URL(self.location.href).searchParams.get('surface') || ''
  const names = [...new Set(raw.split(',').filter(Boolean))].toSorted()
  if (names.length === 0 || names.some((name) => !KNOWN_SURFACES.includes(name))) return null
  return names
}

const SURFACES = registeredSurfaces()
const VERSION = BUILD ? BUILD.manifestHash.slice(0, 16) : null
const CACHE = VERSION && SURFACES ? `mrt-precache-${VERSION}-${SURFACES.join('+')}` : null

const urlOf = (path) => new URL(path, SCOPE).href

/** The entries one surface needs: the shell, the shared list and its own list. */
function requiredFor(surface) {
  if (!BUILD) return []
  return [...BUILD.lists.shell, ...BUILD.lists.shared, ...(BUILD.lists[surface] || [])]
}

/** Everything this registration installs and serves, deduplicated by path. */
function installedEntries() {
  const byPath = new Map()
  for (const surface of SURFACES || []) for (const entry of requiredFor(surface)) byPath.set(entry.path, entry)
  return [...byPath.values()]
}

const SERVED = new Set(installedEntries().map((entry) => urlOf(entry.path)))

async function sha256Hex(buffer) {
  const digest = await crypto.subtle.digest('SHA-256', buffer)
  return [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, '0')).join('')
}

/** Fetch one listed file and check its hash. Resolves to the body, or to a failure with its reason. */
async function fetchChecked(entry) {
  const url = urlOf(entry.path)
  let response
  try {
    response = await fetch(new Request(`${url}?v=${VERSION}`, { cache: 'reload', credentials: 'same-origin' }))
  } catch (err) {
    return { path: entry.path, reason: 'fetch', detail: String(err) }
  }
  if (!response.ok) return { path: entry.path, reason: 'fetch', detail: `HTTP ${response.status}` }
  const body = await response.arrayBuffer()
  const actual = await sha256Hex(body)
  if (actual !== entry.sha256) return { path: entry.path, reason: 'hash', detail: `expected ${entry.sha256}, got ${actual}` }
  return { path: entry.path, url, body, type: response.headers.get('Content-Type') || '' }
}

/** Tell every Gridline page, controlled or not; the page logs it (offline.update_failed). */
async function tellPages(message) {
  const pages = await self.clients.matchAll({ includeUncontrolled: true, type: 'window' })
  // Client.postMessage(message, transfer): the second argument is a transfer
  // list, not a target origin, so the rule written for Window.postMessage
  // does not apply.
  // oxlint-disable-next-line unicorn/require-post-message-target-origin
  for (const page of pages) page.postMessage(message)
}

async function install() {
  if (!BUILD) throw new Error('the precache lists were never injected (tools/inject-sw-manifest.mjs); nothing can be certified')
  if (!SURFACES) throw new Error(`the registration names no known surface: ${self.location.search}`)
  const existed = await caches.has(CACHE)
  const results = await Promise.all(installedEntries().map(fetchChecked))
  const failures = results.filter((r) => r.reason).map(({ path, reason, detail }) => ({ path, reason, detail }))
  if (failures.length === 0) {
    try {
      const cache = await caches.open(CACHE)
      await Promise.all(
        results.map((r) => cache.put(r.url, new Response(r.body, { status: 200, headers: r.type ? { 'Content-Type': r.type } : {} }))),
      )
      return
    } catch (err) {
      failures.push({ path: '(cache)', reason: 'store', detail: String(err) })
    }
  }
  // A cache this install created must not outlive it half full.
  if (!existed) await caches.delete(CACHE)
  await tellPages({ type: 'MRT_INSTALL_FAILED', cacheName: CACHE, failures })
  throw new Error(`install failed for ${failures.length} file(s): ${failures.map((f) => `${f.path} (${f.reason})`).join(', ')}`)
}

self.addEventListener('install', (event) => {
  // No skipWaiting(): a new version waits until every Gridline tab is closed (E22).
  event.waitUntil(install())
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      const keys = await caches.keys()
      // Only Gridline's own older caches (the 0.2.0 mrt-precache-v* and
      // mrt-runtime-v* included). Other pages share Cache Storage (E28).
      await Promise.all(keys.filter((key) => key.startsWith('mrt-') && key !== CACHE).map((key) => caches.delete(key)))
      await self.clients.claim()
    })(),
  )
})

/* Fetch (C5.8). Cross-origin, non-GET, unlisted paths and every navigation
 * other than the app itself go to the network untouched and are never
 * stored. There is no runtime cache. */
self.addEventListener('fetch', (event) => {
  const request = event.request
  if (request.method !== 'GET') return
  const url = new URL(request.url)
  // The cross-origin refusal. Do not add an exception to this (D-023).
  if (url.origin !== self.location.origin) return
  const plain = url.origin + url.pathname

  if (request.mode === 'navigate') {
    // Every hash route is a navigation to the scope root or index.html.
    if (plain !== SCOPE && plain !== urlOf('index.html')) return
    event.respondWith(
      (async () => {
        const shell = await caches.match(urlOf('index.html'), { cacheName: CACHE })
        if (shell) return shell
        try {
          return await fetch(request)
        } catch {
          // The network failed and there is no cached shell: say so in words.
          return new Response('Offline, and the Gridline offline pack is not installed yet. Reconnect once to install it.', {
            status: 503,
            headers: { 'Content-Type': 'text/plain; charset=utf-8' },
          })
        }
      })(),
    )
    return
  }

  if (!SERVED.has(plain)) return
  event.respondWith(
    (async () => (await caches.match(plain, { cacheName: CACHE })) || fetch(request))(),
  )
})

/* Message API. Replies go to event.ports[0] when the page used a
 * MessageChannel, else to event.source.
 *   MRT_QUERY_OFFLINE_READY { surface } -> MRT_OFFLINE_READY_RESULT
 *   MRT_QUERY_VERSION                   -> MRT_VERSION { version, manifestHash, cacheName, surfaces }
 */
function reply(event, payload) {
  const port = event.ports && event.ports[0]
  if (port) port.postMessage(payload)
  // oxlint-disable-next-line unicorn/require-post-message-target-origin
  else if (event.source) event.source.postMessage(payload)
}

/**
 * Every entry the surface needs, checked against this worker's cache by name.
 * Fails closed on any doubt. A surface this registration did not name is
 * ready too when the cache already holds every file it needs: on the laptop
 * the `course` pack holds the whole Companion (its chunk is on the shared
 * list), so after "Switch to the phone Companion" the status must not say
 * "incomplete" while the new worker waits for the tabs to close (fix round
 * 1; SPEC.md C5.1). The fetch handler serves those files from this cache.
 */
async function verifySurface(surface) {
  const required = requiredFor(surface)
  const result = { type: 'MRT_OFFLINE_READY_RESULT', surface, version: VERSION, cacheName: CACHE, ready: false, verified: 0, required: required.length, missing: [], reason: '' }
  if (!BUILD) {
    result.reason = 'build-manifest-not-injected'
    return result
  }
  if (!KNOWN_SURFACES.includes(surface)) {
    result.reason = 'unknown-surface'
    return result
  }
  if (!SURFACES) {
    result.reason = 'surface-not-installed'
    result.missing = required.map((entry) => entry.path)
    return result
  }
  for (const entry of required) {
    // Only what this worker serves counts: a file it does not serve would
    // come from the network, cache or no cache.
    const served = SERVED.has(urlOf(entry.path))
    if (served && (await caches.match(urlOf(entry.path), { cacheName: CACHE }))) result.verified += 1
    else result.missing.push(entry.path)
  }
  result.ready = result.missing.length === 0
  // A surface this registration did not name, with a file missing: a later
  // registration installs it.
  if (result.ready) result.reason = 'verified'
  else result.reason = SURFACES.includes(surface) ? 'incomplete' : 'surface-not-installed'
  return result
}

self.addEventListener('message', (event) => {
  const data = event.data
  if (!data || typeof data.type !== 'string') return
  if (data.type === 'MRT_QUERY_OFFLINE_READY') {
    event.waitUntil((async () => reply(event, await verifySurface(data.surface)))())
  } else if (data.type === 'MRT_QUERY_VERSION') {
    reply(event, { type: 'MRT_VERSION', version: VERSION, manifestHash: BUILD ? BUILD.manifestHash : null, cacheName: CACHE, surfaces: SURFACES })
  }
})
