/*
 * Gridline service worker (SPEC.md C5; ARCHITECTURE.md §5.8; D-070, D-073).
 *
 * Hand-written on purpose (D-033): offline honesty must be provable from a
 * static list, which a caching strategy cannot give. No Workbox, no
 * dependency.
 *
 *  1. One list per surface. tools/inject-sw-manifest.mjs writes BUILD below:
 *     `shell`, `shared`, `course` and `companion`, each entry `{ path,
 *     sha256 }`, path relative to this worker's scope. The page registers
 *     `./sw.js?surface=<sorted surfaces used in this browser>`, and install
 *     fetches only those surfaces (C5.6): the phone never downloads the
 *     desktop surface.
 *  2. Install is all or nothing (C5.4, G2R-39). Every listed file is fetched
 *     with `?v=<first 16 hex of manifestHash>`, so a stale CDN copy of an
 *     unhashed URL (index.html, the icons, the map crop) is not used, and its
 *     SHA-256 is compared with the list. One missing file or one wrong byte
 *     fails the install; the old version keeps serving.
 *  3. The cache name comes from the content: `mrt-precache-<16 hex>-<surfaces
 *     joined by +>` (SPEC-SCHEMAS.md §5.11). It changes exactly when a listed
 *     file or the surface set changes, so an install never writes into the
 *     cache the active worker serves.
 *  4. A new version waits until every Gridline tab is closed (E22). There is
 *     no page-started swap. Activate deletes only the other `mrt-` caches,
 *     because other pages on the origin keep their own (E28).
 *  5. Readiness is asked for, never volunteered: the page shows "Offline pack
 *     ready" only after MRT_QUERY_OFFLINE_READY answers ready for its surface.
 *  6. Nothing cross-origin is ever cached or answered (D-023): licence
 *     position and offline honesty both depend on it.
 */

'use strict'

/* __BUILD_ASSETS_START__ */
/* Generated by tools/inject-sw-manifest.mjs. Do not edit by hand. */
const BUILD = {
  "manifestHash": "23cf8f64bf7c10f8ad2f66777850e12cce245a7e613f1529b98e07ad4393c638",
  "lists": {
    "shell": [
      {
        "path": "icons/icon-192.png",
        "sha256": "f7bf2aaafbba1ebe85937e38b8741b61e49e73660352be204d3aa2f452e29086"
      },
      {
        "path": "icons/icon-512.png",
        "sha256": "69d6e8771c73b16d383d3092106019dd66fdf26aac9f5f5412c13ab6c5cacb5c"
      },
      {
        "path": "icons/maskable-512.png",
        "sha256": "0b5c044a1283ee9f94cd0b0c02b211d199315eb1f2789a7ed271d56ed023bed6"
      },
      {
        "path": "index.html",
        "sha256": "3c0f7d588bf0078513d45c8b1fa57a3d03f855ecf577e8bb04e7e23228c753fc"
      },
      {
        "path": "manifest.webmanifest",
        "sha256": "01f35d7ccc1f9e49bb35daf604d4acc7beb51a17045794a8e1d42543ec738b04"
      }
    ],
    "shared": [
      {
        "path": "assets/companion-B56pDbpM.js",
        "sha256": "a6ee00b1962783934256704dba4c0b1c8f8e9b69e5789d8e4ce9bbc3029c990f"
      },
      {
        "path": "assets/companion-BotiQQVz.css",
        "sha256": "bf5811de8d7c93f4dbd71ba85c24414c33a18bae11010a2ceb7c8af76fc4c7e8"
      },
      {
        "path": "assets/index-DJlCalm6.css",
        "sha256": "5fbeb6f21197edb2d89f7362f6ad65230957fdaa8b4533ca71a3cd7fe858a94c"
      },
      {
        "path": "assets/index-DzfeM71E.js",
        "sha256": "c785847918afcd87abdafe586b60b2c3acae7facea8f78f5075aaffc7989a7af"
      },
      {
        "path": "assets/rolldown-runtime-BpQH8Ho1.js",
        "sha256": "f42a7e25f42fd00b0935f3a7b06f4429238b50b6798b53c273e30d7095f9e94e"
      }
    ],
    "course": [
      {
        "path": "assets/course-CC1m-Lvy.js",
        "sha256": "8020b89152844aae2a7e9456da0c79f1cf648a6fd6df74ee55d260ea04a7a4d8"
      },
      {
        "path": "assets/course-Du0vbjmR.css",
        "sha256": "973e05878c1e2fac7a29e796096120558ccd55be31a607e3489147db3b0675d8"
      },
      {
        "path": "licensed-maps/011e03_scale_distance_crop_v1.png",
        "sha256": "8a1ca00c4bbc95e204995c37cb598daabe1ae85b57be2dd9116153faef55a34d"
      }
    ],
    "companion": []
  }
}
/* __BUILD_ASSETS_END__ */

const KNOWN_SURFACES = ['companion', 'course']
const SCOPE = self.registration.scope

/** The surfaces this registration names, sorted; null when it names one we do not know (fail closed). */
function registeredSurfaces() {
  const raw = new URL(self.location.href).searchParams.get('surface') || ''
  const names = [...new Set(raw.split(',').filter(Boolean))].toSorted()
  if (names.length === 0 || names.some((name) => !KNOWN_SURFACES.includes(name))) return null
  return names
}

const SURFACES = registeredSurfaces()
const VERSION = BUILD ? BUILD.manifestHash.slice(0, 16) : null
const CACHE = VERSION && SURFACES ? `mrt-precache-${VERSION}-${SURFACES.join('+')}` : null

const urlOf = (path) => new URL(path, SCOPE).href

/** The entries one surface needs: the shell, the shared list and its own list. */
function requiredFor(surface) {
  if (!BUILD) return []
  return [...BUILD.lists.shell, ...BUILD.lists.shared, ...(BUILD.lists[surface] || [])]
}

/** Everything this registration installs and serves, deduplicated by path. */
function installedEntries() {
  const byPath = new Map()
  for (const surface of SURFACES || []) for (const entry of requiredFor(surface)) byPath.set(entry.path, entry)
  return [...byPath.values()]
}

const SERVED = new Set(installedEntries().map((entry) => urlOf(entry.path)))

async function sha256Hex(buffer) {
  const digest = await crypto.subtle.digest('SHA-256', buffer)
  return [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, '0')).join('')
}

/** Fetch one listed file and check its hash. Resolves to the body, or to a failure with its reason. */
async function fetchChecked(entry) {
  const url = urlOf(entry.path)
  let response
  try {
    response = await fetch(new Request(`${url}?v=${VERSION}`, { cache: 'reload', credentials: 'same-origin' }))
  } catch (err) {
    return { path: entry.path, reason: 'fetch', detail: String(err) }
  }
  if (!response.ok) return { path: entry.path, reason: 'fetch', detail: `HTTP ${response.status}` }
  const body = await response.arrayBuffer()
  const actual = await sha256Hex(body)
  if (actual !== entry.sha256) return { path: entry.path, reason: 'hash', detail: `expected ${entry.sha256}, got ${actual}` }
  return { path: entry.path, url, body, type: response.headers.get('Content-Type') || '' }
}

/** Tell every Gridline page, controlled or not; the page logs it (offline.update_failed). */
async function tellPages(message) {
  const pages = await self.clients.matchAll({ includeUncontrolled: true, type: 'window' })
  // Client.postMessage(message, transfer): the second argument is a transfer
  // list, not a target origin, so the rule written for Window.postMessage
  // does not apply.
  // oxlint-disable-next-line unicorn/require-post-message-target-origin
  for (const page of pages) page.postMessage(message)
}

async function install() {
  if (!BUILD) throw new Error('the precache lists were never injected (tools/inject-sw-manifest.mjs); nothing can be certified')
  if (!SURFACES) throw new Error(`the registration names no known surface: ${self.location.search}`)
  const existed = await caches.has(CACHE)
  const results = await Promise.all(installedEntries().map(fetchChecked))
  const failures = results.filter((r) => r.reason).map(({ path, reason, detail }) => ({ path, reason, detail }))
  if (failures.length === 0) {
    try {
      const cache = await caches.open(CACHE)
      await Promise.all(
        results.map((r) => cache.put(r.url, new Response(r.body, { status: 200, headers: r.type ? { 'Content-Type': r.type } : {} }))),
      )
      return
    } catch (err) {
      failures.push({ path: '(cache)', reason: 'store', detail: String(err) })
    }
  }
  // A cache this install created must not outlive it half full.
  if (!existed) await caches.delete(CACHE)
  await tellPages({ type: 'MRT_INSTALL_FAILED', cacheName: CACHE, failures })
  throw new Error(`install failed for ${failures.length} file(s): ${failures.map((f) => `${f.path} (${f.reason})`).join(', ')}`)
}

self.addEventListener('install', (event) => {
  // No skipWaiting(): a new version waits until every Gridline tab is closed (E22).
  event.waitUntil(install())
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      const keys = await caches.keys()
      // Only Gridline's own older caches (the 0.2.0 mrt-precache-v* and
      // mrt-runtime-v* included). Other pages share Cache Storage (E28).
      await Promise.all(keys.filter((key) => key.startsWith('mrt-') && key !== CACHE).map((key) => caches.delete(key)))
      await self.clients.claim()
    })(),
  )
})

/* Fetch (C5.8). Cross-origin, non-GET, unlisted paths and every navigation
 * other than the app itself go to the network untouched and are never
 * stored. There is no runtime cache. */
self.addEventListener('fetch', (event) => {
  const request = event.request
  if (request.method !== 'GET') return
  const url = new URL(request.url)
  // The cross-origin refusal. Do not add an exception to this (D-023).
  if (url.origin !== self.location.origin) return
  const plain = url.origin + url.pathname

  if (request.mode === 'navigate') {
    // Every hash route is a navigation to the scope root or index.html.
    if (plain !== SCOPE && plain !== urlOf('index.html')) return
    event.respondWith(
      (async () => {
        const shell = await caches.match(urlOf('index.html'), { cacheName: CACHE })
        if (shell) return shell
        try {
          return await fetch(request)
        } catch {
          // The network failed and there is no cached shell: say so in words.
          return new Response('Offline, and the Gridline offline pack is not installed yet. Reconnect once to install it.', {
            status: 503,
            headers: { 'Content-Type': 'text/plain; charset=utf-8' },
          })
        }
      })(),
    )
    return
  }

  if (!SERVED.has(plain)) return
  event.respondWith(
    (async () => (await caches.match(plain, { cacheName: CACHE })) || fetch(request))(),
  )
})

/* Message API. Replies go to event.ports[0] when the page used a
 * MessageChannel, else to event.source.
 *   MRT_QUERY_OFFLINE_READY { surface } -> MRT_OFFLINE_READY_RESULT
 *   MRT_QUERY_VERSION                   -> MRT_VERSION { version, manifestHash, cacheName, surfaces }
 */
function reply(event, payload) {
  const port = event.ports && event.ports[0]
  if (port) port.postMessage(payload)
  // oxlint-disable-next-line unicorn/require-post-message-target-origin
  else if (event.source) event.source.postMessage(payload)
}

/**
 * Every entry the surface needs, checked against this worker's cache by name.
 * Fails closed on any doubt. A surface this registration did not name is
 * ready too when the cache already holds every file it needs: on the laptop
 * the `course` pack holds the whole Companion (its chunk is on the shared
 * list), so after "Switch to the phone Companion" the status must not say
 * "incomplete" while the new worker waits for the tabs to close (fix round
 * 1; SPEC.md C5.1). The fetch handler serves those files from this cache.
 */
async function verifySurface(surface) {
  const required = requiredFor(surface)
  const result = { type: 'MRT_OFFLINE_READY_RESULT', surface, version: VERSION, cacheName: CACHE, ready: false, verified: 0, required: required.length, missing: [], reason: '' }
  if (!BUILD) {
    result.reason = 'build-manifest-not-injected'
    return result
  }
  if (!KNOWN_SURFACES.includes(surface)) {
    result.reason = 'unknown-surface'
    return result
  }
  if (!SURFACES) {
    result.reason = 'surface-not-installed'
    result.missing = required.map((entry) => entry.path)
    return result
  }
  for (const entry of required) {
    // Only what this worker serves counts: a file it does not serve would
    // come from the network, cache or no cache.
    const served = SERVED.has(urlOf(entry.path))
    if (served && (await caches.match(urlOf(entry.path), { cacheName: CACHE }))) result.verified += 1
    else result.missing.push(entry.path)
  }
  result.ready = result.missing.length === 0
  // A surface this registration did not name, with a file missing: a later
  // registration installs it.
  if (result.ready) result.reason = 'verified'
  else result.reason = SURFACES.includes(surface) ? 'incomplete' : 'surface-not-installed'
  return result
}

self.addEventListener('message', (event) => {
  const data = event.data
  if (!data || typeof data.type !== 'string') return
  if (data.type === 'MRT_QUERY_OFFLINE_READY') {
    event.waitUntil((async () => reply(event, await verifySurface(data.surface)))())
  } else if (data.type === 'MRT_QUERY_VERSION') {
    reply(event, { type: 'MRT_VERSION', version: VERSION, manifestHash: BUILD ? BUILD.manifestHash : null, cacheName: CACHE, surfaces: SURFACES })
  }
})
