"""Build the front page: five stamped screens in the donor look (DECISIONS.md D-A27, CR-21).

Stdlib only. Reads scripts/front_page.config.json and the data the site already has, and writes
one HTML file per screen. Nothing is typed twice: the figures come from data/evidence.json, the
rows from data/registry.json and data/desk.json, the counts from those same rows.

    python scripts/build_front_page.py                # review build -> docs/front-page/
    python scripts/build_front_page.py --root         # promote to the repo root (the owner's go only)
    python scripts/build_front_page.py --check        # build in memory, compare with disk, write nothing
    python scripts/build_front_page.py --only desk    # compare or write one screen only

Exit codes (the Doctor's): 0 built, or --check found the files identical.
                           1 --check found a difference, a screen failed, or the content broke a rule.
                           2 could not look: an input is missing or invalid. Never a pass.

Screens `trading` and `games` are carried from the tier pages by scripts/front_carry.py. If that
module does not exist yet, or raises NotImplementedError, the screen is logged as screen_skipped,
its page is NOT written, and the nav and the Home doors leave it out. A missing page is true; a stub
page is not.

Every run logs to scripts/logs/front-page-YYYYMMDD.jsonl (see front_log.py) and prints the path first.
"""

from __future__ import annotations

import argparse
import sys
import traceback
from pathlib import Path, PurePosixPath

SCRIPTS = Path(__file__).resolve().parent
REPO = SCRIPTS.parent
if str(SCRIPTS) not in sys.path:
    sys.path.insert(0, str(SCRIPTS))          # front_carry is imported lazily from here

from front_figures import read_json                                                    # noqa: E402
from front_log import EXIT_COULD_NOT_LOOK, EXIT_OK, EXIT_RED, CouldNotLook, Refused, get_logger   # noqa: E402
from front_screens import BUILDERS, load_model                                           # noqa: E402
from front_shell import Page, load_icons, render_page                                    # noqa: E402

CONFIG_PATH = SCRIPTS / "front_page.config.json"
ICONS_PATH = SCRIPTS / "front_icons.json"
GENERATED_MARK = "GENERATED by scripts/build_front_page.py"


# -- config -----------------------------------------------------------------------------------------


def load_config() -> dict:
    cfg = read_json(CONFIG_PATH)
    problems = []
    for key in ("outputs", "promotion", "brand", "ui", "assets", "nav", "screens", "home", "rail", "desk"):
        if not isinstance(cfg.get(key), (dict, list)):
            problems.append("missing section %r" % key)
    if problems:
        raise CouldNotLook("%s: %s" % (CONFIG_PATH.name, "; ".join(problems)))
    groups = {g["id"] for g in cfg["nav"]["groups"]}
    seen_ids, seen_out = set(), set()
    for s in cfg["screens"]:
        for key in ("id", "kind", "url", "out", "title", "group", "icon", "description"):
            if not isinstance(s.get(key), str) or not s[key]:
                problems.append("screen %r has no %r" % (s.get("id"), key))
        if s.get("kind") not in ("built", "carried"):
            problems.append("screen %r: kind must be 'built' or 'carried'" % s.get("id"))
        if s.get("kind") == "built" and s.get("id") not in BUILDERS:
            problems.append("screen %r is 'built' but front_screens.py has no builder for it" % s.get("id"))
        if s.get("group") not in groups:
            problems.append("screen %r: group %r is not in nav.groups" % (s.get("id"), s.get("group")))
        if s.get("id") in seen_ids or s.get("out") in seen_out:
            problems.append("screen %r repeats an id or an out path" % s.get("id"))
        seen_ids.add(s.get("id"))
        seen_out.add(s.get("out"))
    if problems:
        raise CouldNotLook("%s: %s" % (CONFIG_PATH.name, "; ".join(problems)))
    return cfg


# -- carried screens --------------------------------------------------------------------------------


def run_carry(screen: dict, ctx: dict, log):
    """(part, status). status is 'ok', 'skipped' (not written, nav leaves it out) or 'failed' (build stops)."""
    sid = screen["id"]
    try:
        import front_carry                                  # lazy: agent C writes it after this file
    except ModuleNotFoundError as err:
        if err.name != "front_carry":
            raise                                           # front_carry exists but needs a module that does not: a real fault
        log.warn("screen_skipped", screen=sid, reason="scripts/front_carry.py does not exist yet")
        return None, "skipped"
    try:
        result = front_carry.carry(sid, ctx)
    except NotImplementedError as err:
        log.warn("screen_skipped", screen=sid, reason="front_carry.carry raised NotImplementedError: %s" % (err or "no detail"))
        return None, "skipped"
    except Exception as err:  # noqa: BLE001 - one carry fault must not hide the other screens' results; it is logged in full
        log.error("screen_failed", screen=sid, error="%s: %s" % (type(err).__name__, err), traceback=traceback.format_exc())
        return None, "failed"
    if not isinstance(result, dict) or not isinstance(result.get("body"), str) or not result["body"].strip():
        log.error("screen_failed", screen=sid, error="front_carry.carry must return {'body': html, 'css': [...], 'scripts': [...]}")
        return None, "failed"
    part = {
        "body": result["body"],
        "css": list(result.get("css") or []),
        "tail": [("src", p) for p in result.get("scripts") or []],
    }
    return part, "ok"


# -- comparing and writing --------------------------------------------------------------------------


def _first_difference(old: bytes, new: bytes) -> int:
    """The 1-based line where two files first differ, for the log. Not a diff, a pointer."""
    old_lines, new_lines = old.split(b"\n"), new.split(b"\n")
    for i in range(max(len(old_lines), len(new_lines))):
        if i >= len(old_lines) or i >= len(new_lines) or old_lines[i] != new_lines[i]:
            return i + 1
    return 0


def guard_promotion(cfg: dict, rels: list, out_dir: Path, log) -> None:
    """--root replaces live pages. Refuse until each is preserved, so nothing the owner has is lost."""
    legacy = cfg["promotion"]["legacy"]
    for rel in rels:
        target = out_dir / rel
        if not target.is_file() or GENERATED_MARK in target.read_text(encoding="utf-8", errors="replace"):
            continue                                        # nothing there, or a page this build wrote
        keep = legacy.get(rel)
        if keep is None:
            raise Refused("%s exists and this build did not write it, and promotion.legacy names no copy of it. Nothing was written." % rel)
        kept = REPO / keep
        live = target.read_bytes().replace(b"\r\n", b"\n")
        if not kept.is_file() or kept.read_bytes().replace(b"\r\n", b"\n") != live:
            raise Refused("promotion: copy %s to %s first (the live page is about to be replaced; the copy is missing or differs). Nothing was written." % (rel, keep))
        log.info("promotion_legacy_ok", page=rel, kept_at=keep)


def sync(pages: dict, out_dir: Path, check: bool, log):
    """Compare each page with disk (LF-normalised) and write the ones that changed. -> (changed, same)."""
    changed, same = [], []
    for rel, text in pages.items():
        target = out_dir / rel
        new = text.replace("\r\n", "\n").encode("utf-8")
        old = target.read_bytes().replace(b"\r\n", b"\n") if target.is_file() else None
        if old == new:
            same.append(rel)
            continue
        changed.append(rel)
        if old is None:
            log.info("check_differs" if check else "page_written", page=rel, reason="not on disk", bytes=len(new))
        else:
            log.info("check_differs" if check else "page_written", page=rel, reason="content differs", first_line=_first_difference(old, new), bytes=len(new))
        if not check:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(new)
    return changed, same


def warn_missing_assets(cfg: dict, built: list, parts: dict, log) -> None:
    """A page that names a file that is not there loads a 404. Say so; do not stop (S and C write them in parallel)."""
    wanted = set(cfg["assets"]["css"]) | set(cfg["assets"]["js"])
    for part in parts.values():
        wanted |= set(part.get("css", [])) | {v for k, v in part.get("tail", []) if k == "src"}
    if any(s["kind"] == "carried" for s in built):
        wanted |= set(cfg["assets"]["css_carried"])
    for rel in sorted(wanted):
        if not (REPO / rel).is_file():
            log.warn("asset_missing", path=rel, reason="a page links this file and it is not in the repo yet")


# -- the build --------------------------------------------------------------------------------------


def run(args, mode: str, log):
    cfg = load_config()
    icons = load_icons(ICONS_PATH)
    model = load_model(REPO, cfg, log)
    screens = cfg["screens"]
    if args.only and args.only not in {s["id"] for s in screens}:
        raise CouldNotLook("--only %s: not a screen id in %s (%s)" % (args.only, CONFIG_PATH.name, ", ".join(s["id"] for s in screens)))

    out_rel = cfg["outputs"][mode]
    out_dir = (REPO / out_rel).resolve()
    up = 0 if out_rel in ("", ".") else len(PurePosixPath(out_rel).parts)

    def prefixes(screen):
        depth = len(PurePosixPath(screen["out"]).parent.parts)
        return "../" * depth, "../" * (depth + up)            # (base: to the output folder, root: to the repo root)

    # 1. Carried screens first: the nav can only list a screen that exists.
    carried, skipped, failed = {}, [], []
    for s in screens:
        if s["kind"] != "carried":
            continue
        base, root = prefixes(s)
        ctx = {"root": root, "base": base, "repo": REPO, "log": log.bind(screen=s["id"]), "mode": mode, "write": not args.check, "screen": s}
        part, status = run_carry(s, ctx, log)
        if status == "ok":
            carried[s["id"]] = part
        elif status == "skipped":
            skipped.append(s["id"])
        else:
            failed.append(s["id"])
    if failed:
        log.error("build_stopped", failed=failed, reason="a carried screen failed, so nothing was written")
        return EXIT_RED, "screen_failed"
    built = [s for s in screens if s["kind"] == "built" or s["id"] in carried]

    # 2. Render every screen that exists.
    pages, parts = {}, {}
    for s in built:
        base, root = prefixes(s)
        pg = Page(cfg, icons, mode, s, built, base, root, model.figs["asof"], model.counts, log, model)
        try:
            part = BUILDERS[s["id"]](pg) if s["kind"] == "built" else carried[s["id"]]
        except KeyError as err:
            log.error("builder_key_missing", screen=s["id"], key=str(err), traceback=traceback.format_exc())
            raise CouldNotLook("screen %r needs the key %s, which is not in scripts/front_page.config.json or the data (traceback in the log)" % (s["id"], err)) from err
        parts[s["id"]] = part
        pages[s["out"]] = (s["id"], render_page(pg, part))
        log.info("screen_built", screen=s["id"], out=s["out"], bytes=len(pages[s["out"]][1].encode("utf-8")))
    warn_missing_assets(cfg, built, parts, log)

    # 3. Write, or compare.
    wanted = {out: text for out, (sid, text) in pages.items() if not args.only or sid == args.only}
    if args.only and not wanted:
        raise CouldNotLook("--only %s: that screen is not part of this build (it was skipped)" % args.only)
    stale = []
    for s in screens:
        if s["id"] in skipped and (out_dir / s["out"]).is_file() and (not args.only or s["id"] == args.only):
            stale.append(s["out"])
            log.warn("stale_page_on_disk", page=s["out"], reason="this run did not build the screen, but an older page is on disk; delete it by hand if it is stale")
    if mode == "root" and not args.check:
        guard_promotion(cfg, list(wanted), out_dir, log)
    changed, same = sync(wanted, out_dir, args.check, log)

    summary = "%s %s: %d page(s) %s, %d unchanged, %d skipped%s" % (
        "check" if args.check else "build", mode, len(changed), "differ" if args.check else "written", len(same), len(skipped),
        " (%s)" % ", ".join(skipped) if skipped else "",
    )
    print(summary, flush=True)
    log.info("build_done", mode=mode, check=args.check, changed=changed, unchanged=same, skipped=skipped, stale=stale)
    if args.check and (changed or stale):
        return EXIT_RED, "check_differs"
    return EXIT_OK, "check_clean" if args.check else "ok"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description="Build the front page (D-A27). Exit 0 built or identical, 1 differs or refused, 2 could not look.")
    parser.add_argument("--root", action="store_true", help="build into the repo root instead of docs/front-page (promotion; the owner's go only)")
    parser.add_argument("--check", action="store_true", help="build in memory, compare with disk, write nothing; exit 1 if any file differs")
    parser.add_argument("--only", metavar="ID", help="compare or write one screen only (the others are still built, so the nav stays whole)")
    args = parser.parse_args(argv)

    try:
        log = get_logger("build_front_page")
    except OSError as err:
        print("cannot write the log (%s). Nothing was built." % err, file=sys.stderr)
        return EXIT_COULD_NOT_LOOK
    mode = "root" if args.root else "review"
    log.info("start", mode=mode, check=args.check, only=args.only)
    try:
        code, outcome = run(args, mode, log)
    except CouldNotLook as err:
        log.error("could_not_look", reason=str(err))
        code, outcome = EXIT_COULD_NOT_LOOK, "could_not_look"
    except Refused as err:
        log.error("refused", reason=str(err))
        code, outcome = EXIT_RED, "refused"
    log.finish(outcome)
    return code


if __name__ == "__main__":
    sys.exit(main())
