"""data/desk-local.js: the Tool Desk's ports and paths, for the owner's machine only (D-A27 addendum b).

js/front/desk.js requests this file only when the Tool Desk is opened from localhost, 127.0.0.1, [::1] or a
file. The public site never asks for it and no page prints these values. The same facts are already in
data/desk.json, which is public; the point of the gate is that no page people read shows them.

The file is generated from data/desk.json (`mine`, keyed by slug, and `extra`, a list with its own slug). Only
a port that is a number from 1 to 65535, and a path or launch note that is a non-empty string, are kept. An entry
with nothing usable is left out: an empty cell is better than a wrong one (SAFE-04).
"""

from __future__ import annotations

import json
from pathlib import Path

from front_figures import read_json

HEADER = (
    "/* GENERATED by scripts/build_front_page.py (scripts/front_local.py) from data/desk.json. Do not edit by hand.\n"
    "   js/front/desk.js loads this file ONLY when the Tool Desk is opened from localhost, 127.0.0.1 or a file.\n"
    "   The public site never requests it and no page prints these values. */\n"
)


def _entry(source: dict, slug: str, log):
    out = {}
    port = source.get("port")
    if isinstance(port, int) and not isinstance(port, bool) and 1 <= port <= 65535:
        out["port"] = port
    elif port is not None:
        log.warn("local_port_ignored", slug=slug, port=repr(port), reason="not a number from 1 to 65535")
    for key in ("path", "launch"):
        value = source.get(key)
        if isinstance(value, str) and value.strip():
            out[key] = value.strip()
    return out


def build(repo: Path, cfg: dict, log) -> dict:
    """{relative path: file text}. The path is relative to the repo root in both the review and the root build."""
    desk = read_json(repo / "data" / "desk.json")
    found = {}
    for slug, source in sorted((desk.get("mine") or {}).items()):
        if isinstance(source, dict):
            entry = _entry(source, slug, log)
            if entry:
                found[slug] = entry
    for source in desk.get("extra") or []:
        if isinstance(source, dict) and isinstance(source.get("slug"), str):
            entry = _entry(source, source["slug"], log)
            if entry:
                found.setdefault(source["slug"], entry)
    text = HEADER + "window.FP_DESK_LOCAL=" + json.dumps(found, sort_keys=True, indent=0, ensure_ascii=True) + ";\n"
    log.info("local_data_built", entries=len(found), with_port=sum(1 for e in found.values() if "port" in e),
             with_path=sum(1 for e in found.values() if "path" in e))
    return {cfg["desk"]["local"]["data_file"]: text}
