"""The shell block and the page wrapper, written once (docs/front-page-design/ARCHITECTURE.md).

Every screen carries the same sidebar and bar. Only three things change from page to page: which
nav link has aria-current, the crumb words in the bar, and the relative prefix on every link. The
nav is rendered from scripts/front_page.config.json, never by JavaScript, so a page whose script
fails still has its navigation (D-A27 item 7).

TWO PREFIXES, because the review build lives two folders down:
    base  from this page to the output folder   (screen-to-screen links: nav, brand, doors, search)
    root  from this page to the repo root       (styles/, js/, data/, atlas/, the hubs)
In a --root build the two are equal. In the review build (docs/front-page/) root is base plus
"../../", so Home links to Rail inside the review tree while a project row still reaches /atlas/.

In the review build a screen link ends in index.html, so the pages also navigate when opened
straight from disk (file:// shows a folder listing for "desk/"). A --root build uses clean URLs.

Anything that needs a script ships `hidden`; js/front/shell.js unhides it. With no script every
link and every row is still there and no control is dead.
"""

from __future__ import annotations

import html
import re
from dataclasses import dataclass
from pathlib import Path, PurePosixPath

from front_figures import read_json
from front_log import CouldNotLook

GENERATED = (
    "<!-- GENERATED by scripts/build_front_page.py from scripts/front_page.config.json. "
    "Do not edit by hand: change the config or the script and rebuild (scripts/FRONT-PAGE.md). -->"
)

# Sets data-theme before first paint: stored choice (fp-theme), else the system setting. A storage
# error leaves the CSS default (light), which is the intended fallback and needs no log.
THEME_SCRIPT = (
    '<script>try{var t=localStorage.getItem("fp-theme");'
    'if(!t&&matchMedia("(prefers-color-scheme: dark)").matches)t="dark";'
    'if(t==="dark")document.documentElement.dataset.theme="dark"}catch(x){}</script>'
)

_BOLD = re.compile(r"\*\*(.+?)\*\*")


def esc_text(value) -> str:
    """Escape for an element's text. Quotes stay as typed, so apostrophes read as apostrophes."""
    return html.escape("" if value is None else str(value), quote=False)


def esc_attr(value) -> str:
    """Escape for a double-quoted attribute value."""
    return html.escape("" if value is None else str(value), quote=True)


def rich(value) -> str:
    """Config copy to HTML: escape everything, then turn **word** into <b>word</b>."""
    return _BOLD.sub(r"<b>\1</b>", esc_text(value))


def fill(template: str, values: dict) -> str:
    """Fill {placeholders}. An unknown placeholder is a config error, not a silent blank."""
    try:
        return template.format_map(values)
    except (KeyError, IndexError, ValueError) as err:
        raise CouldNotLook("config text %r has a placeholder this build cannot fill: %s" % (template[:60], err)) from err


def load_icons(path: Path) -> dict:
    data = read_json(path)
    icons = data.get("icons") if isinstance(data, dict) else None
    if not isinstance(icons, dict) or not icons:
        raise CouldNotLook("%s has no 'icons' object" % path)
    return icons


@dataclass
class Page:
    """Everything one page needs to write its own shell. The orchestrator makes one per screen."""

    cfg: dict
    icons: dict
    mode: str                 # "review" or "root"
    screen: dict              # the config entry of this page
    built: list               # config entries of every screen that exists in this build
    base: str
    root: str
    asof: str | None
    counts: dict              # {"projects": n, "tools": m}, computed, never typed
    log: object = None        # front_log.Logger
    model: object = None      # front_screens.Model

    def icon(self, name: str, size: int = 16) -> str:
        """Inline SVG. The presentation attributes make it draw correctly even where no rule styles it."""
        shapes = self.icons.get(name)
        if shapes is None:
            raise CouldNotLook("icon %r is not in scripts/front_icons.json" % name)
        inner = "".join(
            "<%s %s/>" % (tag, " ".join('%s="%s"' % (k, esc_attr(v)) for k, v in attrs.items())) for tag, attrs in shapes
        )
        return (
            '<svg xmlns="http://www.w3.org/2000/svg" width="%d" height="%d" viewBox="0 0 24 24" fill="none" '
            'stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" '
            'aria-hidden="true" focusable="false">%s</svg>' % (size, size, inner)
        )

    def href(self, screen_id: str) -> str | None:
        """Link to another built screen, or None when that screen is not part of this build."""
        target = next((s for s in self.built if s["id"] == screen_id), None)
        if target is None:
            return None
        folder = PurePosixPath(target["out"]).parent
        path = "" if str(folder) == "." else folder.as_posix() + "/"
        tail = "index.html" if self.mode == "review" else ""
        return (self.base + path + tail) or "./"


def nav_html(pg: Page) -> str:
    """The sidebar nav: groups from config, only screens that exist, exactly one aria-current."""
    groups = []
    for group in pg.cfg["nav"]["groups"]:
        items = [s for s in pg.built if s["group"] == group["id"]]
        if not items:
            continue
        label_id = "fp-ng%d" % len(groups)
        links = []
        for s in items:
            current = ' aria-current="page"' if s["id"] == pg.screen["id"] else ""
            links.append(
                '<li><a href="%s"%s>%s<span>%s</span></a></li>'
                % (esc_attr(pg.href(s["id"])), current, pg.icon(s["icon"]), esc_text(s["title"]))
            )
        groups.append(
            '<div class="fp-navgroup" role="group" aria-labelledby="%s"><span class="fp-navgroup-k" id="%s">%s</span>'
            "<ul>%s</ul></div>" % (label_id, label_id, esc_text(group["label"]), "".join(links))
        )
    return '<nav class="fp-nav" id="fp-nav" aria-label="%s">%s</nav>' % (esc_attr(pg.cfg["ui"]["nav_aria"]), "".join(groups))


def find_html(pg: Page) -> str:
    """The bar's search form. It submits to the Tool Desk, which filters on ?q=. Hidden until a script runs."""
    desk = pg.href("desk")
    if desk is None:
        return ""      # no Tool Desk in this build, so a search box would lead nowhere
    ui = pg.cfg["ui"]
    placeholder = fill(ui["search_placeholder"], pg.counts)
    return (
        '<form class="fp-find" data-chrome="find" role="search" action="%s" method="get" hidden>%s'
        '<input type="search" name="q" id="fp-q" placeholder="%s" aria-label="%s" autocomplete="off">'
        '<kbd aria-hidden="true">/</kbd></form>'
        % (esc_attr(desk), pg.icon("search"), esc_attr(placeholder), esc_attr(ui["search_aria"]))
    )


def shell_open(pg: Page) -> str:
    """From <body> to the opening of the page track. The screen body goes after this."""
    cfg, ui, brand = pg.cfg, pg.cfg["ui"], pg.cfg["brand"]
    group = next(g["label"] for g in cfg["nav"]["groups"] if g["id"] == pg.screen["group"])
    sidefoot = ""
    if pg.asof:
        sidefoot = '\n  <div class="fp-sidefoot">%s</div>' % esc_text(fill(ui["sidefoot"], {"asof": pg.asof}))
    return (
        '<body data-screen="%s">\n'
        '<a class="fp-skip" href="#fp-main">%s</a>\n'
        '<aside class="fp-side" data-chrome="identity_navigation" aria-label="%s">\n'
        '  <div class="fp-brandrow">\n'
        '    <a class="fp-brand" href="%s"><span class="fp-tile fp-tile-brand">%s</span>'
        '<span class="fp-two"><b>%s</b><small>%s</small></span></a>\n'
        '    <button type="button" class="fp-menu-btn" id="fp-menu-btn" aria-expanded="false" aria-controls="fp-nav" hidden>'
        "%s %s</button>\n"
        "  </div>\n"
        "  %s%s\n"
        "</aside>\n"
        '<div class="fp-sheet">\n'
        '  <header class="fp-bar" data-chrome="orientation_progress">\n'
        '    <span class="fp-crumb"><span>%s</span><b>%s</b></span>\n'
        '    <div class="fp-end">\n'
        "      %s\n"
        '      <button type="button" class="fp-theme" id="fp-theme" aria-pressed="false" title="%s" hidden>'
        '<span class="fp-dot" aria-hidden="true"></span>%s</button>\n'
        "    </div>\n"
        "  </header>\n"
        '  <main class="fp-main" id="fp-main"><div class="fp-track">\n'
        % (
            esc_attr(pg.screen["id"]),
            esc_text(ui["skip"]),
            esc_attr(ui["site_aria"]),
            esc_attr(pg.href("home") or "./"),
            esc_text(brand["tile"]),
            esc_text(brand["name"]),
            esc_text(brand["tagline"]),
            pg.icon("menu"),
            esc_text(ui["menu"]),
            nav_html(pg),
            sidefoot,
            esc_text(group),
            esc_text(pg.screen["title"]),
            find_html(pg),
            esc_attr(ui["theme_title"]),
            esc_text(ui["theme"]),
        )
    )


def _head(pg: Page, part: dict) -> str:
    cfg, screen = pg.cfg, pg.screen
    suffix = cfg["brand"]["title_suffix"]
    title = screen.get("page_title") or "%s · %s" % (screen["title"], suffix)
    description = fill(screen["description"], pg.counts)
    # The review copy sits under docs/, which Pages also serves, so it is never indexed.
    robots = screen.get("robots") or ("noindex" if pg.mode == "review" else None)
    css = list(cfg["assets"]["css"])
    if screen["kind"] == "carried":
        css += cfg["assets"]["css_carried"]
    css += part.get("css", [])
    lines = [
        '<meta charset="utf-8">',
        '<meta name="viewport" content="width=device-width,initial-scale=1">',
        "<title>%s</title>" % esc_text(title),
        '<meta name="description" content="%s">' % esc_attr(description),
    ]
    if robots:
        lines.append('<meta name="robots" content="%s">' % esc_attr(robots))
    # No icon file exists yet. An empty data URI stops the browser asking for /favicon.ico (a 404).
    lines.append('<link rel="icon" href="data:,">')
    lines.append(THEME_SCRIPT)
    lines += ['<link rel="stylesheet" href="%s">' % esc_attr(pg.root + path) for path in css]
    return "<head>\n%s\n</head>" % "\n".join(lines)


def _tail(pg: Page, part: dict) -> str:
    """The scripts at the end of <body>: shell.js first, then whatever the screen needs, in order."""
    items = [("src", path) for path in pg.cfg["assets"]["js"]] + list(part.get("tail", []))
    lines = []
    for kind, value in items:
        if kind == "src":
            lines.append('<script src="%s"></script>' % esc_attr(pg.root + value))
        else:
            lines.append("<script>%s</script>" % value)
    return "\n".join(lines)


def render_page(pg: Page, part: dict) -> str:
    """The whole document for one screen. `part` is {"body": html, "css": [...], "tail": [(kind, value)]}."""
    return (
        "<!doctype html>\n%s\n"
        '<html lang="en">\n%s\n%s%s\n</div></main>\n</div>\n%s\n</body>\n</html>\n'
        % (GENERATED, _head(pg, part), shell_open(pg), part["body"], _tail(pg, part))
    )
