"""Carry a built tier page into a front-page screen (DECISIONS.md D-A27, CR-21).

scripts/build_front_page.py calls carry(screen_id, ctx) for the screens "trading" (docs/tier-2-case) and
"games" (docs/tier-3). The step reads the tier page, keeps its <style> and <body>, drops its scripts,
and returns {"body": html, "css": [paths], "scripts": [paths]}. It writes the generated stylesheet
(styles/front/carry-<screen>.css) and copies the tier scripts to js/front/ itself; the builder only links them.

What it changes in the CSS, in order (all of it driven by scripts/front_carry.config.json):
  1. comments go; every selector is scoped under .fp-carry-<screen>; :root becomes the scope class;
     html and body rules are dropped; @keyframes names stay as they are.
  2. the palette variable declarations go (front.bridge.css defines the names from the tokens).
  3. @media (min/max-width) becomes @container, so a piece follows its box and not the window.
  4. every colour literal is mapped to a token. A literal with no mapping stops the carry
     (carry_literal_unmapped). Nothing raw is ever passed through.
  5. position: fixed or sticky must be listed in the config, or the carry stops.

--check: build_front_page.py passes ctx["write"] = False. Then nothing is written; a file that is missing
or differs raises StaleCarry, which the builder logs as screen_failed (exit 1). Deterministic: no
timestamps in the output, so a second run changes nothing. Standard library only. Manual: scripts/FRONT-PAGE-CARRY.md.
"""

from __future__ import annotations

import html
import json
import re
from pathlib import Path

CONFIG_PATH = Path(__file__).resolve().parent / "front_carry.config.json"
GENERATED = "GENERATED by scripts/front_carry.py"

HEX = re.compile(r"#[0-9a-fA-F]{3,8}\b")
FUNC = re.compile(r"\b(?:rgba?|hsla?|hwb|lab|lch|oklab|oklch|color)\(")
RGB_ARGS = re.compile(r"^rgba?\(\s*(\d{1,3})\s*,\s*(\d{1,3})\s*,\s*(\d{1,3})\s*(?:,\s*([\d.]+%?)\s*)?\)$", re.I)
WORD = re.compile(r"(?<![\w-])[a-z]+(?![\w(-])")
URL = re.compile(r"url\([^)]*\)")
VAR = re.compile(r"var\([^)]*\)")
COLOUR_PROPS = re.compile(
    r"^(color|background(-color|-image)?|border(-(top|right|bottom|left))?(-color)?|outline(-color)?|fill|stroke|"
    r"box-shadow|text-shadow|text-decoration(-color)?|caret-color|accent-color|column-rule(-color)?|stop-color|flood-color)$")
MEDIA_WIDTH = re.compile(r"^@media\s*\(\s*(min|max)-width\s*:\s*(\d+(?:\.\d+)?px)\s*\)$")
PATH_ATTR = r"(?:href|src|data-attract|poster|action)"


class CarryError(Exception):
    """The carry cannot make a true page. The builder logs screen_failed and exits 1."""


class StaleCarry(CarryError):
    """--check: a file this step writes is missing or differs from a fresh carry."""


# -- small CSS readers ------------------------------------------------------------------------------


def _split(text: str, sep: str) -> list:
    """Split on `sep` outside (), [] and quotes."""
    parts, cur, depth, quote = [], [], 0, ""
    for ch in text:
        if quote:
            quote = "" if ch == quote else quote
        elif ch in "\"'":
            quote = ch
        elif ch in "([":
            depth += 1
        elif ch in ")]":
            depth -= 1
        elif ch == sep and depth == 0:
            parts.append("".join(cur))
            cur = []
            continue
        cur.append(ch)
    parts.append("".join(cur))
    return parts


def _blocks(css: str) -> list:
    """[(prelude, body)] at one level: body is the text between a matching { }. Strings may hold braces."""
    out, i, n = [], 0, len(css)
    while True:
        j = css.find("{", i)
        if j < 0:
            if css[i:].strip():
                raise CarryError("css: text after the last block: %r" % css[i:i + 60].strip())
            return out
        depth, k, quote = 1, j + 1, ""
        while k < n and depth:
            ch = css[k]
            if quote:
                quote = "" if ch == quote else quote
            elif ch in "\"'":
                quote = ch
            elif ch == "{":
                depth += 1
            elif ch == "}":
                depth -= 1
            k += 1
        if depth:
            raise CarryError("css: unbalanced braces after %r" % css[i:i + 60].strip())
        out.append((css[i:j].strip(), css[j + 1:k - 1]))
        i = k


def _colours(value: str, named: set, any_named: bool) -> list:
    """(start, end) of each raw colour in a declaration value, in order. url(...) is skipped."""
    masked = URL.sub(lambda m: " " * len(m.group()), value)
    spans = [(m.start(), m.end()) for m in HEX.finditer(masked)]
    for m in FUNC.finditer(masked):
        depth, i = 1, m.end()
        while i < len(masked) and depth:
            depth += (masked[i] == "(") - (masked[i] == ")")
            i += 1
        spans.append((m.start(), i))
    if any_named:
        plain = VAR.sub(lambda m: " " * len(m.group()), masked)
        spans += [(m.start(), m.end()) for m in WORD.finditer(plain) if m.group() in named]
    return sorted(spans)


def _norm_hex(text: str) -> str:
    t = text.strip().lower()
    return "#" + "".join(c * 2 for c in t[1:]) if re.fullmatch(r"#[0-9a-f]{3}", t) else t


# -- the CSS pass -----------------------------------------------------------------------------------


class _Css:
    """One screen's stylesheet. Findings are collected and raised together by finish(), so one run names every fault."""

    def __init__(self, scope: str, cfg: dict, scr: dict, log, problems: list):
        self.scope, self.log, self.cfg, self.scr, self.problems = scope, log, cfg, scr, problems
        self.container = scr.get("container")             # optional: only a screen with width queries needs one
        self.literals = cfg["literals"] + scr.get("literals", [])
        self.rewrites = cfg["rewrites"] + scr.get("rewrites", [])
        self.overrides = ([{"selector": self.container["selector"], "set": {
            "container-type": "inline-size", "container-name": self.container["name"]}}] if self.container else []) + scr.get("overrides", [])
        self.allow_fixed = scr.get("allow_fixed", {})
        self.drop = set(scr["drop_selectors"])
        self.palette = set(cfg["palette_names"])
        self.named = set(cfg["named_colours"].split())
        self.used = {"literals": set(), "rewrites": set(), "overrides": set()}
        self.seen_palette, self.dropped, self.mapped = set(), [], []
        self.stats = {"rules": 0, "selectors_dropped": 0, "literals_mapped": 0, "container_queries": 0}

    def problem(self, event: str, **ctx) -> None:
        self.log.error(event, **ctx)
        self.problems.append(event)

    def run(self, css: str, extra: str) -> str:
        lines = []
        for text in (css, extra):
            lines += self._level(_blocks(re.sub(r"/\*.*?\*/", "", text, flags=re.S)), 0, False)
        for i, ov in enumerate(self.overrides):
            if i not in self.used["overrides"]:          # the source has no such rule: add it
                self.used["overrides"].add(i)
                body = "; ".join("%s: %s" % kv for kv in ov["set"].items()) + ";"
                lines.append("%s %s { %s }" % (self.scope, ov["selector"], body))
                self.log.info("carry_override_appended", selector=ov["selector"], reason="no rule with that selector in the tier CSS")
        return "\n".join(lines) + "\n"

    def finish(self) -> None:
        """Say what was done and what matched nothing; raise if anything broke a rule (markup faults included)."""
        for kind, items in (("literals", self.literals), ("rewrites", self.rewrites), ("overrides", self.overrides)):
            for i, item in enumerate(items):
                if i not in self.used[kind]:
                    self.log.warn("carry_config_unused", kind=kind, entry=item.get("selector") or item.get("value"), property=item.get("property"),
                                  reason="it matched nothing in the tier CSS; the tier may have changed")
        if self.dropped:
            self.log.info("carry_selectors_dropped", selectors=self.dropped, reason="listed in drop_selectors (the shell rebuilds the page head, or resets it), or an html/body rule (the shell owns the page ground)")
        if self.seen_palette:
            self.log.info("carry_palette_dropped", names=sorted(self.seen_palette), reason="front.bridge.css defines these names from the tokens")
        self.log.info("carry_literals_mapped", count=len(self.mapped), mapped=self.mapped)
        if self.problems:
            raise CarryError("%d fault(s) (%s); see the log" % (len(self.problems), ", ".join(sorted(set(self.problems)))))

    def _level(self, blocks: list, depth: int, keyframes: bool) -> list:
        pad, out = "  " * depth, []
        for prelude, body in blocks:
            prelude = " ".join(prelude.split())
            if prelude.startswith("@"):
                out += self._at_rule(prelude, body, depth)
            elif keyframes:
                out.append("%s%s { %s }" % (pad, prelude, self._decls([prelude], body)))
            else:
                line = self._rule(prelude, body, depth)
                if line:
                    out.append(line)
        return out

    def _at_rule(self, prelude: str, body: str, depth: int) -> list:
        name = re.match(r"@[\w-]+", prelude).group(0)
        if name in ("@keyframes", "@-webkit-keyframes"):
            inner = self._level(_blocks(body), depth + 1, True)          # step selectors (from, 20%) stay as written
        elif name in ("@media", "@supports", "@container", "@layer"):
            if name == "@media":
                prelude = self._media(prelude)
            inner = self._level(_blocks(body), depth + 1, False)
        else:
            self.problem("carry_at_rule_unsupported", at_rule=prelude)
            return []
        pad = "  " * depth
        return ["%s%s {" % (pad, prelude)] + inner + ["%s}" % pad] if inner else []

    def _media(self, prelude: str) -> str:
        m = MEDIA_WIDTH.match(prelude)
        if m and self.container:
            self.stats["container_queries"] += 1
            return "@container %s (%s-width: %s)" % (self.container["name"], m.group(1), m.group(2))
        return re.sub(r"\(\s*([\w-]+)\s*:\s*", r"(\1: ", prelude)

    def _scope(self, sel: str):
        if sel.startswith(":root"):
            return self.scope + sel[5:]
        if re.match(r"(html|body)(?![\w-])", sel):
            return None
        return "%s %s" % (self.scope, sel)

    def _rule(self, prelude: str, body: str, depth: int):
        self.stats["rules"] += 1
        kept, scoped = [], []
        for sel in (" ".join(s.split()) for s in _split(prelude, ",") if s.strip()):
            scope_sel = None if sel in self.drop else self._scope(sel)
            if scope_sel is None:
                self.stats["selectors_dropped"] += 1
                self.dropped.append(sel)
                continue
            kept.append(sel)
            scoped.append(scope_sel)
        decls = self._decls(kept, body) if kept else ""
        return "%s%s { %s }" % ("  " * depth, ", ".join(scoped), decls) if decls else None

    def _decls(self, selectors: list, body: str) -> str:
        items = []
        for raw in _split(body, ";"):
            if not raw.strip():
                continue
            prop, sep, value = raw.partition(":")
            prop, value = prop.strip(), value.strip()
            if not sep or not prop:
                self.problem("carry_css_malformed", selectors=selectors, declaration=raw.strip()[:80])
                continue
            if prop in self.palette:
                self.seen_palette.add(prop)
                continue
            if '"' not in value and "'" not in value:
                value = " ".join(value.split())
            value = self._rewrite(selectors, prop, value)
            items.append([prop, self._literals(selectors, prop, value)])
        for i, ov in enumerate(self.overrides):
            if ov["selector"] not in selectors:
                continue
            self.used["overrides"].add(i)
            for key, new in ov["set"].items():
                hit = next((it for it in items if it[0] == key), None)
                if hit:
                    hit[1] = new
                else:
                    items.append([key, new])
        for prop, value in items:
            if prop == "position" and re.match(r"(fixed|sticky)\b", value):
                why = next((self.allow_fixed[s] for s in selectors if s in self.allow_fixed), "")
                if why:
                    self.log.info("carry_fixed_kept", selectors=selectors, position=value, reason=why)
                else:
                    self.problem("carry_fixed_position", selectors=selectors, position=value,
                                 reason="the shell has three chrome clusters; list the selector in allow_fixed with a reason, or remove the rule")
        return " ".join("%s: %s;" % (p, v) for p, v in items)

    def _rewrite(self, selectors: list, prop: str, value: str) -> str:
        for i, rw in enumerate(self.rewrites):
            if rw["from"] in value and re.search(rw["property"], prop) and any(re.search(rw["selector"], s) for s in selectors):
                value = value.replace(rw["from"], rw["to"])
                self.used["rewrites"].add(i)
        return value

    def _literals(self, selectors: list, prop: str, value: str) -> str:
        for start, end in reversed(_colours(value, self.named, bool(COLOUR_PROPS.match(prop)))):
            lit = value[start:end]
            to = self._token_for(lit, selectors, prop)
            if to is None:
                self.problem("carry_literal_unmapped", literal=lit, selectors=selectors, property=prop,
                             reason="add an entry to literals (or an rgb_tokens triple) in front_carry.config.json")
                continue
            self.stats["literals_mapped"] += 1
            self.mapped.append("%s -> %s (%s %s)" % (lit, to, selectors[0] if selectors else "", prop))
            value = value[:start] + to + value[end:]
        return value

    def _token_for(self, lit: str, selectors: list, prop: str):
        key = _norm_hex(lit)
        for i, rule in enumerate(self.literals):
            if _norm_hex(rule["value"]) == key and re.search(rule.get("property", ""), prop) \
                    and ("selector" not in rule or rule["selector"] in selectors):
                self.used["literals"].add(i)
                return rule["to"]
        m = RGB_ARGS.match(lit)
        token = self.cfg["rgb_tokens"].get("%s,%s,%s" % m.group(1, 2, 3)) if m else None
        if not token:
            return None
        alpha = m.group(4) or "1"
        pct = float(alpha[:-1]) if alpha.endswith("%") else float(alpha) * 100
        if pct >= 99.995:
            return "var(%s)" % token
        return "color-mix(in srgb, var(%s) %s%%, transparent)" % (token, ("%.3f" % pct).rstrip("0").rstrip("."))


# -- the markup pass --------------------------------------------------------------------------------


def _markup(src: str, scr: dict, root: str, mode: str, repo: Path, log, problems: list):
    """(css source, head html, body html) from one tier page."""
    css = "\n".join(re.findall(r"<style[^>]*>(.*?)</style>", src, re.S))
    m = re.search(r"<body[^>]*>(.*)</body>", src, re.S)
    if not css.strip() or not m:
        raise CarryError("the tier page has no <style> or no <body>")
    body = re.sub(r"<script[^>]*>.*?</script>", "", m.group(1), flags=re.S)
    body = re.sub(r"<!--.*?-->", "", body, flags=re.S)
    parts = {}
    for key in ("kicker", "title", "lede"):
        spec = scr["head"][key]
        hit = re.search(spec["pattern"], body, re.S)
        if not hit:
            raise CarryError("page head: %r matched nothing in the tier body (pattern %s)" % (key, spec["pattern"]))
        parts[key] = html.escape(spec["text"]) if spec.get("text") else " ".join(hit.group(1).split())
        body = body[:hit.start()] + body[hit.end():]
    head = ('<div class="fp-pagehead"><div><p class="fp-kicker">%(kicker)s</p><h1 class="fp-title">%(title)s</h1>\n'
            '<p class="fp-lede">%(lede)s</p></div></div>' % parts)

    body, n_main = re.subn(r"<(/?)main\b", r"<\1div", body)
    if n_main:
        log.info("carry_main_to_div", count=n_main, reason="the shell already has the page's one <main>")
    # An iframe with no src is the same blank document; wall.js sets .src when it opens. The page then names no non-file link.
    body, n_blank = re.subn(r'(<iframe\b[^>]*?)\s+src="about:blank"', r"\1", body)
    if n_blank:
        log.info("carry_iframe_src_dropped", count=n_blank, reason="src=about:blank is what an iframe with no src already is")
    for item in scr.get("redact", []):
        if item["from"] not in body:
            log.warn("carry_config_unused", kind="redact", entry=item["from"], reason="it matched nothing in the tier body; the tier may have changed")
            continue
        body = body.replace(item["from"], item["to"])
        log.info("carry_text_redacted", text=item["from"], to=item["to"], reason=item["why"])
    # `insert`: markup the tier page does not have, put in front of an anchor string. Used where a part
    # is dropped on a narrow screen and something must say so (the part's replacement exists elsewhere).
    for item in scr.get("insert", []):
        if item["before"] not in body:
            log.warn("carry_config_unused", kind="insert", entry=item["before"], reason="it matched nothing in the tier body; the tier may have changed")
            continue
        body = body.replace(item["before"], item["html"] + item["before"], 1)
        log.info("carry_html_inserted", before=item["before"], reason=item["why"])

    def fix(hit):
        rest = hit.group(3)
        target = repo / re.split(r"[?#]", rest)[0]
        if not target.exists():
            problems.append("carry_path_missing")
            log.error("carry_path_missing", path=rest, reason="a link or frame in the tier page points at a file that is not in the repo")
        elif mode == "review" and rest.endswith("/") and (target / "index.html").is_file():
            rest += "index.html"        # as the builder does for its own links: opened from disk, a bare directory shows a listing, not the page
        return "%s=%s%s%s%s" % (hit.group(1), hit.group(2), root, rest, hit.group(2))

    body = re.sub(r"\b(%s)=([\"'])\.\./\.\./([^\"']*)\2" % PATH_ATTR, fix, body)
    absolute = "|".join(["#", "https?:", "mailto:", "about:", "data:"] + ([re.escape(root)] if root else []))
    for rel in re.findall(r"\b%s=[\"'](?!%s)([^\"']*)[\"']" % (PATH_ATTR, absolute), body):
        problems.append("carry_path_unresolved")
        log.error("carry_path_unresolved", path=rel, reason="a relative path the carry does not rewrite; it would break at the new depth")
    body = "\n".join(line.rstrip() for line in body.strip().splitlines())
    body = re.sub(r"\n{3,}", "\n\n", body)

    ids = re.findall(r'\bid="([^"]+)"', head + body)
    for dup in sorted({i for i in ids if ids.count(i) > 1} | {i for i in ids if i.startswith("fp-")}):
        problems.append("carry_id_clash")
        log.error("carry_id_clash", id=dup, reason="an id repeats, or starts with fp-, which the shell uses")
    return css, head, body


# -- files ------------------------------------------------------------------------------------------


def _sync(repo: Path, rel: str, data: bytes, write: bool, log):
    """Write `data` to repo/rel if it differs. With write False, only compare. -> a stale reason, or None."""
    path = repo / rel
    old = path.read_bytes().replace(b"\r\n", b"\n") if path.is_file() else None
    if old == data:
        log.info("carry_file_unchanged", path=rel)
        return None
    reason = "missing" if old is None else "differs from a fresh carry"
    if not write:
        log.error("carry_file_stale", path=rel, reason=reason)
        return "%s (%s)" % (rel, reason)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)
    log.info("carry_file_written", path=rel, bytes=len(data), reason=reason)
    return None


def carry(screen_id: str, ctx: dict) -> dict:
    """The contract with scripts/build_front_page.py: {"body": html, "css": [paths], "scripts": [paths]}."""
    log, repo, root, write = ctx["log"], Path(ctx["repo"]), ctx["root"], ctx.get("write", True)
    cfg = json.loads(CONFIG_PATH.read_text(encoding="utf-8"))
    scr = cfg["screens"].get(screen_id)
    if scr is None:
        raise NotImplementedError("front_carry.config.json has no screen %r" % screen_id)
    source = repo / scr["source"]
    if not source.is_file():
        log.error("tier_page_missing", screen=screen_id, path=scr["source"], reason="the page this screen is carried from is not in the repo")
        raise CarryError("tier page missing: %s" % scr["source"])
    log.info("carry_start", screen=screen_id, source=scr["source"], write=write)

    problems: list = []
    scope = ".fp-carry-" + screen_id
    css_src, head, body = _markup(source.read_text(encoding="utf-8"), scr, root, ctx.get("mode", "review"), repo, log, problems)
    for attr in re.findall(r'\b(?:style|fill|stroke|stop-color|flood-color)="([^"]*)"', body):
        if _colours(attr, set(cfg["named_colours"].split()), True):
            problems.append("carry_literal_unmapped")
            log.error("carry_literal_unmapped", literal=attr, selectors=["(inline attribute)"], property="style",
                      reason="a colour inside the markup cannot be mapped; move it into the tier CSS")
    sheet = _Css(scope, cfg, scr, log, problems)
    css_out = sheet.run(css_src, scr.get("extra_css", ""))
    sheet.finish()                                   # raises if the markup or the CSS broke a rule; nothing is written then

    header = ("/* %s from %s and scripts/front_carry.config.json. Do not edit by hand: change the config or the script, then run\n"
              "   python scripts/build_front_page.py. Every selector sits under %s. Palette variables are not declared here;\n"
              "   styles/front/front.bridge.css defines them from the tokens, and every colour below is a token. */\n"
              % (GENERATED, scr["source"], scope))
    files = {scr["css_out"]: (header + css_out).encode("utf-8")}
    for item in scr["scripts"]:
        if not (repo / item["from"]).is_file():
            log.error("tier_script_missing", screen=screen_id, path=item["from"], reason="a script this screen copies is not in the repo")
            raise CarryError("tier script missing: %s" % item["from"])
        files[item["to"]] = (repo / item["from"]).read_bytes().replace(b"\r\n", b"\n")
    stale = [s for s in (_sync(repo, rel, data, write, log) for rel, data in files.items()) if s]
    if stale:
        raise StaleCarry("generated file(s) out of date: %s. Run python scripts/build_front_page.py" % "; ".join(stale))

    log.info("carry_done", screen=screen_id, **sheet.stats, css_bytes=len(css_out), body_bytes=len(body))
    wrapper = '<div class="fp-carry fp-carry-%s">\n%s\n</div>' % (screen_id, body)
    return {"body": head + "\n" + wrapper, "css": [scr["css_out"]], "scripts": [i["to"] for i in scr["scripts"]]}
