import {
  friezeAllSvg,
  friezeGroups,
  friezeStripSvg,
  mirrorRotationSvg,
  wallpaperGroups,
  wallpaperNote,
  wallpaperSampleSvg
} from "../renderers/symmetry.js";

const ids = new Set([
  "mirror-and-rotation",
  "frieze-seven-ways",
  "wallpaper-seventeen",
  "alhambra-count"
]);

const verification = {
  "mirror-and-rotation": {
    scope: "Exact isometry construction",
    method: "Every copy is the one motif mapped by a coordinate transform; deterministic tests check that reflecting twice and completing each rotation orbit return the motif exactly."
  },
  "frieze-seven-ways": {
    scope: "Exact isometry construction",
    method: "All seven strips repeat one asymmetric motif under coordinate transforms; deterministic tests check each group's defining operation and that no two copies overlap."
  },
  "wallpaper-seventeen": {
    scope: "Exact isometry construction · labeled subset",
    method: "Each patch is generated from one motif by the group's translations and point operations; a deterministic test checks the p4m quarter-turn invariance."
  },
  "alhambra-count": {
    scope: "Exact isometry construction · illustrative figure",
    method: "The figure shows the seven frieze strips generated by coordinate transforms; the counting question itself is settled by the cited literature, not by this drawing."
  }
};

const mirrorStatus = {
  identity: "One motif, no copy. The group has a single element.",
  mirror: "The reflected copy answers across the dashed axis. Reflect twice and you are home.",
  rotate2: "A half-turn about the marked centre. Two turns return the motif exactly.",
  rotate3: "Three copies, 120° apart. The orbit closes after three turns.",
  rotate4: "Four copies, 90° apart. The orbit closes after four turns."
};

export const isSymmetryTopic = (id) => ids.has(id);

function controlsFor(topicId) {
  if (topicId === "mirror-and-rotation") {
    return `<div class="tiling-controls" aria-label="Choose a symmetry operation">
      <button data-sym="identity">Identity</button>
      <button data-sym="mirror">Mirror</button>
      <button data-sym="rotate2">Half-turn</button>
      <button data-sym="rotate3">Third-turn</button>
      <button data-sym="rotate4">Quarter-turn</button>
    </div>`;
  }
  if (topicId === "frieze-seven-ways") {
    return `<div class="tiling-controls" aria-label="Choose one of the seven frieze groups">${friezeGroups.map((group) =>
      `<button data-frieze="${group.name}">${group.name} · ${group.label}</button>`
    ).join("")}</div>`;
  }
  if (topicId === "wallpaper-seventeen") {
    return `<div class="tiling-controls" aria-label="Choose one of four sample wallpaper groups">${wallpaperGroups.map((group) =>
      `<button data-wallpaper="${group.name}">${group.name}</button>`
    ).join("")}</div>`;
  }
  return "";
}

function initialStage(topicId) {
  if (topicId === "mirror-and-rotation") return mirrorRotationSvg("identity");
  if (topicId === "frieze-seven-ways") return friezeStripSvg("p1");
  if (topicId === "wallpaper-seventeen") return wallpaperSampleSvg("p1");
  return friezeAllSvg();
}

export function symmetryVisual(topicId) {
  const check = verification[topicId];
  const note = topicId === "wallpaper-seventeen"
    ? `<p class="tiling-note">${wallpaperNote()} · the count of seventeen rests on the cited proofs</p>`
    : "";
  const staticStatus = topicId === "alhambra-count"
    ? "Seven strips from one motif. The wallpaper count works the same way, in two directions at once."
    : "";
  return `<div class="tiling-lab" data-topic="${topicId}">
    <div data-tiling-stage>${initialStage(topicId)}</div>
    ${controlsFor(topicId)}
    ${note}
    <p class="tiling-status" aria-live="polite">${staticStatus}</p>
    <p class="tiling-audit"><span>Verified geometry · ${check.scope}</span>${check.method}</p>
  </div>`;
}

export function mountSymmetryVisual(root, topicId) {
  const lab = root.querySelector(".tiling-lab");
  const stage = lab.querySelector("[data-tiling-stage]");
  const status = lab.querySelector(".tiling-status");

  lab.querySelectorAll("[data-sym]").forEach((button) => button.addEventListener("click", () => {
    const state = button.dataset.sym;
    stage.innerHTML = mirrorRotationSvg(state);
    status.textContent = mirrorStatus[state];
    lab.querySelectorAll("[data-sym]").forEach((item) => item.classList.toggle("is-selected", item === button));
  }));

  lab.querySelectorAll("[data-frieze]").forEach((button) => button.addEventListener("click", () => {
    const group = friezeGroups.find((entry) => entry.name === button.dataset.frieze);
    stage.innerHTML = friezeStripSvg(group.name);
    status.textContent = `${group.name} · “the ${group.label}” — ${group.detail}.`;
    lab.querySelectorAll("[data-frieze]").forEach((item) => item.classList.toggle("is-selected", item === button));
  }));

  lab.querySelectorAll("[data-wallpaper]").forEach((button) => button.addEventListener("click", () => {
    const group = wallpaperGroups.find((entry) => entry.name === button.dataset.wallpaper);
    stage.innerHTML = wallpaperSampleSvg(group.name);
    status.textContent = `${group.name} — ${group.label}. One motif, one lattice, one point group.`;
    lab.querySelectorAll("[data-wallpaper]").forEach((item) => item.classList.toggle("is-selected", item === button));
  }));

  lab.querySelector('[data-sym="identity"]')?.click();
  lab.querySelector('[data-frieze="p1"]')?.click();
  lab.querySelector('[data-wallpaper="p1"]')?.click();
}
