import { regularInteriorAngle, tessellationSvg, vertexCount } from "../renderers/tessellation.js?v=0.8.0";

const ids = new Set([
  "regular-plane-tilings",
  "hexagonal-circle-packing",
  "kashan-star-cross",
  "penrose-rhombs",
  "escher-plane-division",
  "tetris-tetrominoes"
]);

const verification = {
  "regular-plane-tilings": {
    scope: "Exact plane tiling",
    method: "Coordinates are checked for equal edges, single coverage, and no interior overlap."
  },
  "hexagonal-circle-packing": {
    scope: "Exact lattice packing",
    method: "Equal radii and every nearest-centre distance are checked; gaps between circles are intentional."
  },
  "kashan-star-cross": {
    scope: "Exact analytical reconstruction",
    method: "Stars and crosses reuse the same boundary points and exactly fill each square-grid unit cell."
  },
  "penrose-rhombs": {
    scope: "Valid finite Penrose patch",
    method: "Generated by de Bruijn’s pentagrid projection; equal rhomb edges, paired interior edges, coverage, and overlap are checked."
  },
  "escher-plane-division": {
    scope: "Exact translated-boundary tiling",
    method: "Each curved boundary is copied by the same translation, so adjacent tiles share it point for point."
  },
  "tetris-tetrominoes": {
    scope: "Exact piece enumeration",
    method: "All seven one-sided tetrominoes are shown; every connected piece contains exactly four grid cells."
  }
};

export const isTessellationTopic = (id) => ids.has(id);

function controlsFor(topicId) {
  if (topicId === "regular-plane-tilings") {
    return `<div class="tiling-controls" aria-label="Choose regular polygon"><button data-sides="3">Triangle</button><button data-sides="4">Square</button><button data-sides="6">Hexagon</button></div>`;
  }
  if (topicId === "kashan-star-cross") {
    return `<div class="tiling-controls" aria-label="Inspect star and cross tile families"><button data-tile-mode="pattern">Together</button><button data-tile-mode="stars">Star tile</button><button data-tile-mode="crosses">Cross tile</button></div>`;
  }
  if (topicId === "escher-plane-division") {
    return `<label class="deform-control">Boundary translation <output>12</output><input type="range" min="0" max="28" value="12" step="1"></label>`;
  }
  return "";
}

export function tessellationVisual(topicId) {
  const check = verification[topicId];
  return `<div class="tiling-lab" data-topic="${topicId}">
    <div data-tiling-stage>${tessellationSvg(topicId)}</div>
    ${controlsFor(topicId)}
    <p class="tiling-status" aria-live="polite"></p>
    <p class="tiling-audit"><span>Verified geometry · ${check.scope}</span>${check.method}</p>
  </div>`;
}

export function mountTessellationVisual(root, topicId) {
  const lab = root.querySelector(".tiling-lab");
  const stage = lab.querySelector("[data-tiling-stage]");
  const status = lab.querySelector(".tiling-status");

  lab.querySelectorAll("[data-sides]").forEach((button) => button.addEventListener("click", () => {
    const sides = Number(button.dataset.sides);
    stage.innerHTML = tessellationSvg(topicId, { sides });
    const angle = regularInteriorAngle(sides);
    const count = vertexCount(sides);
    status.textContent = `${angle}° × ${count} = 360° · exact shared edges, no gap, no overlap`;
    lab.querySelectorAll("[data-sides]").forEach((item) => item.classList.toggle("is-selected", item === button));
  }));

  lab.querySelectorAll("[data-tile-mode]").forEach((button) => button.addEventListener("click", () => {
    const mode = button.dataset.tileMode;
    stage.innerHTML = tessellationSvg(topicId, { mode });
    status.textContent = mode === "pattern"
      ? "Eight-pointed stars and cross tiles share every boundary."
      : `One ${mode === "stars" ? "star" : "cross"} tile is illuminated inside the complete edge-to-edge pattern.`;
    lab.querySelectorAll("[data-tile-mode]").forEach((item) => item.classList.toggle("is-selected", item === button));
  }));

  const input = lab.querySelector("input");
  if (input) input.addEventListener("input", () => {
    stage.innerHTML = tessellationSvg(topicId, { deformation: input.value });
    lab.querySelector("output").value = input.value;
    status.textContent = `The boundary and its translated copy remain identical at ${input.value} units of deformation.`;
  });

  lab.querySelector("[data-sides]")?.click();
  lab.querySelector('[data-tile-mode="pattern"]')?.click();
}
